TheLenderRD/Controllers/CalcularController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Linq;
using System.Threading.Tasks;
using TheLenderRD.Domain.Dto;
using TheLenderRD.Domain.Services;

namespace TheLenderRD.Presentation.Controllers
{
    public class CalcularController : Controller
    {
        private readonly IConfiguration _configuration;

        public CalcularController(IConfiguration configuration)
        {
            _configuration = configuration;
        }


        // GET: CalcularController
        [HttpGet]
        public async Task<ActionResult> Cuotas()
        {
            ViewBag.Months = await ConsumeApi.ConsumeApi
                .GetInstance(_configuration)
                .CallApiGETAsync<MonthDto>("api/month");

            return View();
        }

        // POST: CalcularController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Cuotas(QueryDto query)
        {
            var Rates = await ConsumeApi.ConsumeApi
                .GetInstance(_configuration)
                .CallApiGETAsync<AgeRageDto>("api/agerate");

            var age = Calculations.CalculateAge(query.DateOfBirth);

            var higher = Rates.Where(x => x.Age > age).ToList();
            var less = Rates.Where(x => x.Age <= age).ToList();

            ViewBag.Months = await ConsumeApi.ConsumeApi
                    .GetInstance(_configuration)
                    .CallApiGETAsync<MonthDto>("api/month");

            if (higher.Count != 0 && less.Count != 0)
            {
                query.ConsultationDate = DateTime.Now;

                var request = await ConsumeApi.ConsumeApi
                   .GetInstance(_configuration).CallApiPOSTAsync<QueryDto>("api/Calculation", query);

                if (request == "InternalServerError")
                {
                    ViewBag.Error = "Error en el servidor.";

                    return View(query);
                }
                else if (request == "NotFound")
                {
                    ViewBag.Error = "El recurso que esta solicitando no se a encontrado.";

                    return View(query);
                }
                else if (request == "BadRequest")
                {
                    ViewBag.Error = "Peticion incorrecta.";

                    return View();
                }
                else if (request == "NoContent")
                {
                    ViewBag.Successful = "Cálculo exitoso";

                    return View();
                }
            }

            if (higher.Count == 0)
                ViewBag.Error = "Favor pasar por una de nuestras sucursales para evaluar su caso.";
            else if (less.Count == 0)
                ViewBag.Error = "Lo sentimos aun no cuenta con la edad para solicitar este producto";

            return View(query);
        }
    }
}

TheLenderRD/Views/Calcular/Cuotas.cshtml
@model TheLenderRD.Domain.Dto.QueryDto?

@{
    ViewData["Title"] = "Home Page";

    var monsths = new List<SelectListItem>();

    foreach (TheLenderRD.Domain.Dto.MonthDto month in ViewBag.Months)
    {
        monsths.Add(new SelectListItem { Text = month.Description, Value = $"{month.Value}",  });
    }
}



<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

<h2 style="color:red;">@ViewBag.Error</h2>
<h2 style="color:green;">@ViewBag.Successful</h2>
<hr />
<br />


@using (Html.BeginForm("Cuotas", "Calcular", FormMethod.Post, new { @style = "border: 1px solid black; border-radius: 15px 15px; padding: 5px;" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">

        <label>Fecha de nacimiento</label>

        @Html.EditorFor(Model => Model.DateOfBirth)

    </div>

    <div class="form-group">

        <label>Monto del préstamo</label>

        @Html.EditorFor(Model => Model.LoanAmount)

    </div>

    <div class="form-group">

        <label>Meses de préstamo</label>

        @Html.DropDownListFor(Model => Model.LoanMonths, monsths, "LoanAmount")

    </div>

    <input type="submit" value="Consultar" class="btn-primary" />
}

TheLenderRD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - TheLenderRD</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </head>

    <body>

        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container"> 

                    <label class="navbar-brand" >The Lender RD</label>

                </div>
            </nav>
        </header>

        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - TheLenderRD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)

    </body>

</html>